# Generated by Django 2.0.2 on 2018-03-04 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0002_auto_20170414_1456'),
        ('players', '0002_auto_20170414_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='community',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='communities.Community'),
        ),
        migrations.AlterUniqueTogether(
            name='team',
            unique_together={('name', 'community')},
        ),
    ]
