# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-26 02:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winner_object_id', models.PositiveIntegerField()),
                ('loser_object_id', models.PositiveIntegerField()),
                ('winner_goals', models.IntegerField()),
                ('loser_goals', models.IntegerField()),
                ('loser_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loser', to='contenttypes.ContentType')),
                ('winner_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winner', to='contenttypes.ContentType')),
            ],
        ),
    ]
