# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-14 13:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='loser_content_type',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='loser', to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='match',
            name='loser_object_id',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='match',
            name='winner_content_type',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='winner', to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='match',
            name='winner_object_id',
            field=models.PositiveIntegerField(editable=False),
        ),
    ]
