# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-14 14:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0002_auto_20170414_1456'),
        ('matches', '0002_auto_20170414_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='community',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='communities.Community'),
            preserve_default=False,
        ),
    ]
